"""Zero-edit auto-instrumentation.

When ``zerodiff record --include PATTERN`` runs a command, the child process
installs an import hook (via an injected ``sitecustomize``) that wraps every
public module-level function of matching modules with the recorder. The
legacy source is never touched and the driver script needs no zerodiff import.

Scope (v1): public module-level functions of filesystem-based modules.
Class methods and closures are not auto-instrumented; use ``zerodiff.wrap``
or the decorator for those.
"""

import fnmatch
import importlib.machinery
import inspect
import os
import sys
from typing import List, Optional

from . import recorder

ENV_INCLUDE = "ZERODIFF_INCLUDE"


def matches(fullname: str, patterns: List[str]) -> bool:
    for pat in patterns:
        if fullname == pat or fullname.startswith(pat + ".") or \
                fnmatch.fnmatchcase(fullname, pat):
            return True
    return False


def instrument_module(module) -> int:
    """Wrap public module-level functions defined in this module.
    Returns the number of boundaries instrumented."""
    count = 0
    for name, obj in list(vars(module).items()):
        if name.startswith("_"):
            continue
        if not inspect.isfunction(obj):
            continue
        if getattr(obj, "__module__", None) != module.__name__:
            continue  # imported from elsewhere; not this module's behavior
        if getattr(obj, "__zerodiff_wrapped__", None) is not None:
            continue
        if obj.__qualname__ != name:
            continue  # nested/class function that leaked to module level
        setattr(module, name, recorder.record(obj))
        count += 1
    return count


class _WrappingLoader:
    def __init__(self, inner) -> None:
        self._inner = inner

    def create_module(self, spec):
        create = getattr(self._inner, "create_module", None)
        return create(spec) if create is not None else None

    def exec_module(self, module):
        self._inner.exec_module(module)
        try:
            instrument_module(module)
        except Exception:
            pass  # instrumentation must never break the host program

    def __getattr__(self, name):
        return getattr(self._inner, name)


class ZeroDiffFinder:
    """Meta-path finder that instruments matching modules as they load.

    Uses PathFinder directly (filesystem modules only), which avoids
    re-entering the meta path and keeps the hook recursion-free.
    """

    def __init__(self, patterns: List[str]) -> None:
        self.patterns = patterns

    def find_spec(self, fullname, path=None, target=None):
        if not matches(fullname, self.patterns):
            return None
        spec = importlib.machinery.PathFinder.find_spec(fullname, path)
        if spec is None or spec.loader is None:
            return None
        if not hasattr(spec.loader, "exec_module"):
            return None
        spec.loader = _WrappingLoader(spec.loader)
        return spec


def install(patterns: List[str]) -> Optional[ZeroDiffFinder]:
    if not patterns:
        return None
    finder = ZeroDiffFinder(patterns)
    sys.meta_path.insert(0, finder)
    return finder


def install_from_env() -> Optional[ZeroDiffFinder]:
    raw = os.environ.get(ENV_INCLUDE, "")
    patterns = [p.strip() for p in raw.split(",") if p.strip()]
    return install(patterns)


# content of the sitecustomize.py that `zerodiff record --include` injects
# into the child process via a temporary PYTHONPATH entry
SITECUSTOMIZE = """\
# generated by zerodiff record --include; safe to ignore
try:
    import os
    if os.environ.get("ZERODIFF_INCLUDE"):
        import zerodiff.autohook
        zerodiff.autohook.install_from_env()
except Exception:
    pass
"""
